[versions]
agp = "9.0.0"
kotlin = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2026.01.00"
navigation = "2.9.6"
serialization = "1.10.0"
camerax = "1.5.2"
coil = "3.3.0"
ksp = "2.3.4"
hilt = "2.59"
media3 = "1.7.1"
paging = "3.3.6"
paging-compose = "3.4.0-rc01"
datastore = "1.2.0"
room = "2.8.4"
material-expressive = "1.5.0-alpha10"
lottie = "6.7.1"
work = "2.11.0"
hilt-ext = "1.3.0"
retrofit = "3.0.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3"}
androidx-material3-expressvie = {group = "androidx.compose.material3",name = "material3",version.ref = "material-expressive"}
androidx-material3-icons = {module = "androidx.compose.material:material-icons-core",version.ref = "material-expressive"}
androidx-navigation = {module = "androidx.navigation:navigation-compose",version.ref = "navigation"}
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization"}
# Contains the basic camera functionality such as SurfaceRequest
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "camerax" }
# Contains the CameraXViewfinder composable
androidx-camera-compose = { module = "androidx.camera:camera-compose", version.ref = "camerax" }
# Allows us to bind the camera preview to our UI lifecycle
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax" }
# The specific camera implementation that renders the preview
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
androidx-camera-extensions = {module = "androidx.camera:camera-extensions",version.ref = "camerax"}
androidx-camera-video= {module = "androidx.camera:camera-video",version.ref = "camerax"}
coil-compose = {module = "io.coil-kt.coil3:coil-compose",version.ref = "coil"}
coil-network = {module = "io.coil-kt.coil3:coil-network-okhttp",version.ref = "coil"}
hilt-compiler = {module = "com.google.dagger:hilt-compiler",version.ref = "hilt"}
hilt-android = {module = "com.google.dagger:hilt-android",version.ref = "hilt"}
hilt-navigation-compose = {module = "androidx.hilt:hilt-navigation-compose",version.ref = "hilt-ext"}
androidx-media3-exoplayer = {module = "androidx.media3:media3-exoplayer",version.ref = "media3"}
androidx-media3-exoplayer-dash  = {module = "androidx.media3:media3-exoplayer-dash",version.ref = "media3"}
androidx-media3-ui = {module = "androidx.media3:media3-ui",version.ref = "media3"}
androidx-media3-compose = {module = "androidx.media3:media3-ui-compose",version.ref = "media3"}
androidx-paging-runtime = {module ="androidx.paging:paging-runtime",version.ref = "paging"}
androidx-paging-compose = {module ="androidx.paging:paging-compose",version.ref = "paging-compose"}
androidx-datastore-preferences = {module = "androidx.datastore:datastore-preferences",version.ref = "datastore"}
androidx-room-runtime = {module = "androidx.room:room-runtime",version.ref = "room"}
androidx-room-compiler = {module = "androidx.room:room-compiler",version.ref = "room"}
androidx-room-ktx = {module = "androidx.room:room-ktx",version.ref = "room"}
androidx-room-paging = {module = "androidx.room:room-paging",version.ref = "room"}
dotlottie-android = {module = "com.airbnb.android:lottie-compose",version.ref = "lottie"}

androidx-work-runtime = {module = "androidx.work:work-runtime-ktx",version.ref = "work"}
androidx-hilt-work = {module = "androidx.hilt:hilt-work",version.ref = "hilt-ext"}
androidx-hilt-work-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-ext" }

squareup-retrofit = {module = "com.squareup.retrofit2:retrofit",version.ref = "retrofit"}
retrofit-gson-convertor = {module = "com.squareup.retrofit2:converter-gson",version.ref = "retrofit"}






[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-ksp = {id = "com.google.devtools.ksp",version.ref = "ksp"}
dagger-hilt-android = { id ="com.google.dagger.hilt.android",version.ref = "hilt"}

